### ISSUE TITLE
Should we keep o-dom?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-dom#8]
See my comment here: https://github.com/Financial-Times/o-dom/issues/1#issuecomment-65088620

I'm seeing a dependency that I'm not sure we need to keep anymore, should we keep it or kill it?

**Comment by wheresrhys** [comment]
@kaelig I've come round to deprecation. As it is o-dom is little more than another semver to  maintain

**Comment by kaelig** [comment]
Note that there's a lot of dependents: next-wrapper o-author-alerts o-ft-header o-gallery o-hierarchical-nav o-layers o-overlay o-share o-table o-tabs

**Comment by callumlocke** [comment]
The readme says o-dom shouldn't have features that replicate querySelector etc. But I think there's a good case for providing convenience wrappers around certain native features, if the native feature has a poorly designed API.

I often end up writing the following wrapper functions in many projects:

```js
// qSA wrapper that works more like jQuery - excluding the base element,
// and returning a real array
function selectAll(selector, base=document) {
  return Array.prototype.slice.apply(base.querySelectorAll(selector))
    .filter(el => el !== base);
}

// makes stuff like this more readable:
var info = selectAll('.foo').map(el => el.dataset.bar);


// same thing but for a single element
function select(selector, base=document) {
  var el = base.querySelector(selector);
  if (el === within) return selectAll(selector, el)[0] || null;
  return el;
}
```

If o-dom had those functions (`select` and `selectAll`) I would use it all the time. If it remains exclusively for DOM things that have no native/polyfillable equivalent, I don't see much use for it, because that's a tiny number of things.

**Comment by AlbertoElias** [comment]
I think we've been regularly against having helper like modules, so I'm in favour of deprecating o-dom

**Comment by wheresrhys** [comment]
We've had a very long running debate about this sort of thing in next. So far we have an n-util placeholder library for css helper classes (not sure if it's in prod yet @i-like-robots ?). We've also entertained the idea of adding some js helpers here too, not necessarily limited to the DOM https://github.com/Financial-Times/n-util/blob/master/main.js.

My personal feeling is origami, with the help of dom-delegate, fetch (is this an origami recommendation for ajax?) and  the polyfill service, provides a good, pretty much as easy to use alternative to most of jquery's features. The exception to this is DOM querying, traversal and manipulation. Given that one of origami's main aims is to ease developer pain it's a shame we don't do better on this. If we're worried about being too opinionated why not emulate a subset of the jquery api (very stable for 8 years or so and with widespread familiarity, so about as uncontroversial as non-standards opinions can be).

**Comment by callumlocke** [comment]
> If we're worried about being too opinionated why not emulate a subset of the jquery api

Do you mean having a jQuery-like collection object (or array subclass) with methods that work on multiple elements at once?

**Comment by wheresrhys** [comment]
The more I think about it the less of jQuery I'd want to emulate.

**Comment by triblondon** [comment]
I'm moderately in favour of keeping o-dom: there is obvious demand for it given the number of dependents.  JS native features for DOM traversal are still far more clunky than jQuery, so I'm also not opposed to providing some convenience wrapper methods as long as they are well thought through. Let's not have a proliferation of methods that have wildly differing argument patterns, return values, etc.

**Comment by callumlocke** [comment]
> The more I think about it the less of jQuery I'd want to emulate.

I agree. The only benefits I can see in implementing a subset of jQuery are:

1. collections that let you do things like addClass to multiple elements at once
– but we can just forEach over stuff, I prefer doing this anyway

2. nicer names/signatures for some methods, like `attr` instead of `getAttribute/setAttribute`, and `find` instead of `querySelectorAll`
– but there's value in using the native APIs directly and being familiar with them. The only exception for me is querySelector and querySelectorAll, which I end up wrapping almost every time I use them anyway, so I think we should provide solid, canonical wrappers for them in o-dom (if others feel the same pain)

**Comment by wheresrhys** [comment]
I think traversal (especially handling the cases where an element isn't there when you expected it to be) is where jQuery's api offers big gains. Like you say, the native APIs (other than being long-winded) are fine for most other things

**Comment by onishiweb** [comment]
Closing this as there are no plans as yet to deprecate the module, will discuss at the next summit when we look at the dependants (o-gallery, o-tabs, o-layers).
